"fragen": "to ask",
      "machen": "to do/make",
      "kaufen": "to buy",
      "suchen": "to search/look for",
      "schicken": "to send",
      "packen": "to pack",
      "zahlen": "to pay",
      "bauen": "to build",
      "sagen": "to say",
      "arbeiten": "to work",
      "rauchen": "to smoke",
      "baden": "to bathe",
      "sparen": "to save",
      "wohnen": "to live/reside",
      "enden": "to end",
      "antworten": "to answer",
      "spielen": "to play",
      "kosten": "to cost",
      "mieten": "to rent",
      "reisen": "to travel",
      "passen": "to fit/suit",
      "duschen": "to shower",
      "putzen": "to clean",
      "heiraten": "to marry",
      "warten": "to wait",
      "stellen": "to place/put",
      "öffnen": "to open",
      "feiern": "to celebrate",
      "hören": "to hear",
      "tanzen": "to dance",
      "Einkaufsliste": "shopping list",
      "Stofftasche": "cloth bag",
      "Plastiktüte": "plastic bag",
      "Wechselgeld": "change",
      "Karte": "card",
      "EC-Karte": "cash card (debit card)",
      "Kreditkarte": "credit card",
      "Kundenkarte": "customer card",
      "Kassenbon / Kassenzettel": "sales receipt",
      "Lebensmittel": "groceries",
      "Kleidung": "clothes",
      "Elektronik": "electronics",
      "Möbel": "furniture",
      "Dekoration": "decoration",
      "Waage": "scales",
      "Kilogramm": "kilogram",
      "Gramm": "gram",
      "Milliliter": "millilitre",
      "Liter": "litre",
      "Zentimeter": "centimetre",
      "Meter": "meter",
      "Länge": "length",
      "Höhe": "height",
      "Breite": "width",
      "Tiefe": "depth",
      "Größe": "size",
      "Ich trinke": "I drink",
      "Wir lernen": "We learn",
      "Carlos wohnt": "Carlos lives",
      "Mein Freund kommt": "My friend comes",
      "Der Apfelkuchen schmeckt": "The apple cake tastes",
      "Mein Zimmer ist": "My room is",
      "Barbara hat zwei": "Barbara has two",
      "viel": "Much/Many",
      "hier": "Here",
      "fertig": "Ready/Finished",
      "nicht": "Not",
      "sehr gut": "Very good",
      "schnell": "Fast",
      "groß": "Big",
      "drum": "Therefore",
      "hell": "Bright",
      "jung": "Young",
      "falsch": "Wrong",
      "Hunger": "Hunger",
      "Ökonomie": "Economics",
      "Kuchen": "Cake",
      "Humor": "Humor",
      "Chemie": "Chemistry",
      "Kaffee": "Coffee",
      "Dach": "Roof",
      "Wörter": "Words",
      "Musik": "Music",
      "Vokabeln": "Vocabulary",
      "Tee": "Tea",
      "Küche": "Kitchen",
      "Grammatik": "Grammar",
      "Studenten": "Students",
      "Brüder": "Brothers",
      "Geld": "Money",
      "Schwestern": "Sisters",
      "Zeit": "Time",
      "Mai": "May",
      "Abend": "Evening",
      "Nacht": "Night",
      "Stunde": "Hour",
      "Tagen": "Days",
      "Montag": "Monday",
      "Mitternacht": "Midnight",
      "Sommer": "Summer",
      "Mineralwasser": "Mineral water",
      "Tomatensuppe": "Tomato soup",
      "Orangensaft": "Orange juice",
      "Suppe": "Soup",
      "Steak": "Steak",
      "Pizza": "Pizza",
      "trinkt": "Drinks",
      "bleiben": "Stay",
      "ist": "Is",
      "leben": "Live",
      "kennst": "Know",
      "kommt": "Comes",
      "hat": "Has",
      "bin": "Am",
      "haben": "Have",
      "sind": "Are",
      "habt": "Have (plural)",
      "seid": "Are (plural)",
      "hast": "Have (singular)",
      "bist": "Are (singular)",
      "ihm": "Him",
      "ihr": "Her/You (formal)",
      "ihnen": "Them",
      "uns": "Us",
      "euch": "You (plural)"